const VOCAB = [
// ── Greetings ──
{k:'おはよう',r:'ohayou',e:'Good morning',b:'শুভ সকাল',c:'greetings'},
{k:'こんにちは',r:'konnichiwa',e:'Hello / Good afternoon',b:'হ্যালো / শুভ অপরাহ্ন',c:'greetings'},
{k:'こんばんは',r:'konbanwa',e:'Good evening',b:'শুভ সন্ধ্যা',c:'greetings'},
{k:'おやすみ',r:'oyasumi',e:'Good night',b:'শুভ রাত্রি',c:'greetings'},
{k:'ありがとう',r:'arigatou',e:'Thank you',b:'ধন্যবাদ',c:'greetings'},
{k:'すみません',r:'sumimasen',e:'Excuse me / Sorry',b:'মাফ করবেন',c:'greetings'},
{k:'はい',r:'hai',e:'Yes',b:'হ্যাঁ',c:'greetings'},
{k:'いいえ',r:'iie',e:'No',b:'না',c:'greetings'},
{k:'さようなら',r:'sayounara',e:'Goodbye',b:'বিদায়',c:'greetings'},
{k:'またね',r:'mata ne',e:'See you later',b:'পরে দেখা হবে',c:'greetings'},
{k:'はじめまして',r:'hajimemashite',e:'Nice to meet you',b:'আপনার সাথে পরিচিত হয়ে খুশি',c:'greetings'},
{k:'よろしく',r:'yoroshiku',e:'Please be kind to me',b:'আমার প্রতি দয়ালু থাকবেন',c:'greetings'},
{k:'おげんきですか',r:'ogenki desu ka',e:'How are you?',b:'আপনি কেমন আছেন?',c:'greetings'},
{k:'げんきです',r:'genki desu',e:"I'm fine",b:'আমি ভালো আছি',c:'greetings'},
{k:'おねがいします',r:'onegaishimasu',e:'Please / I request',b:'অনুগ্রহ করে / দয়া করে',c:'greetings'},
// ── Numbers ──
{k:'ぜろ',r:'zero',e:'0 (zero)',b:'শূন্য',c:'numbers'},
{k:'いち',r:'ichi',e:'1 (one)',b:'এক',c:'numbers'},
{k:'に',r:'ni',e:'2 (two)',b:'দুই',c:'numbers'},
{k:'さん',r:'san',e:'3 (three)',b:'তিন',c:'numbers'},
{k:'し / よん',r:'shi / yon',e:'4 (four)',b:'চার',c:'numbers'},
{k:'ご',r:'go',e:'5 (five)',b:'পাঁচ',c:'numbers'},
{k:'ろく',r:'roku',e:'6 (six)',b:'ছয়',c:'numbers'},
{k:'しち / なな',r:'shichi / nana',e:'7 (seven)',b:'সাত',c:'numbers'},
{k:'はち',r:'hachi',e:'8 (eight)',b:'আট',c:'numbers'},
{k:'きゅう / く',r:'kyuu / ku',e:'9 (nine)',b:'নয়',c:'numbers'},
{k:'じゅう',r:'juu',e:'10 (ten)',b:'দশ',c:'numbers'},
{k:'じゅういち',r:'juuichi',e:'11 (eleven)',b:'এগারো',c:'numbers'},
{k:'じゅうに',r:'juuni',e:'12 (twelve)',b:'বারো',c:'numbers'},
{k:'にじゅう',r:'nijuu',e:'20 (twenty)',b:'বিশ',c:'numbers'},
{k:'ひゃく',r:'hyaku',e:'100 (hundred)',b:'একশত',c:'numbers'},
{k:'せん',r:'sen',e:'1000 (thousand)',b:'এক হাজার',c:'numbers'},
{k:'まん',r:'man',e:'10000 (ten thousand)',b:'দশ হাজার',c:'numbers'},
// ── Time ──
{k:'いま',r:'ima',e:'now',b:'এখন',c:'time'},
{k:'きょう',r:'kyou',e:'today',b:'আজ',c:'time'},
{k:'あした',r:'ashita',e:'tomorrow',b:'আগামীকাল',c:'time'},
{k:'きのう',r:'kinou',e:'yesterday',b:'গতকাল',c:'time'},
{k:'おととい',r:'ototoi',e:'day before yesterday',b:'পরশু',c:'time'},
{k:'あさって',r:'asatte',e:'day after tomorrow',b:'আগামী পরশু',c:'time'},
{k:'あさ',r:'asa',e:'morning',b:'সকাল',c:'time'},
{k:'ひる',r:'hiru',e:'noon / daytime',b:'দুপুর',c:'time'},
{k:'よる',r:'yoru',e:'night / evening',b:'রাত / সন্ধ্যা',c:'time'},
{k:'ゆうがた',r:'yuugata',e:'early evening',b:'সন্ধ্যা',c:'time'},
{k:'まいにち',r:'mainichi',e:'every day',b:'প্রতিদিন',c:'time'},
{k:'まいあさ',r:'maiasa',e:'every morning',b:'প্রতি সকাল',c:'time'},
{k:'まいばん',r:'maiban',e:'every evening',b:'প্রতি সন্ধ্যা',c:'time'},
{k:'ことし',r:'kotoshi',e:'this year',b:'এই বছর',c:'time'},
{k:'らいねん',r:'rainen',e:'next year',b:'আগামী বছর',c:'time'},
{k:'きょねん',r:'kyonen',e:'last year',b:'গত বছর',c:'time'},
{k:'こんしゅう',r:'konshuu',e:'this week',b:'এই সপ্তাহ',c:'time'},
{k:'らいしゅう',r:'raishuu',e:'next week',b:'আগামী সপ্তাহ',c:'time'},
{k:'せんしゅう',r:'senshuu',e:'last week',b:'গত সপ্তাহ',c:'time'},
{k:'ごぜん',r:'gozen',e:'AM / morning',b:'পূর্বাহ্ন (AM)',c:'time'},
{k:'ごご',r:'gogo',e:'PM / afternoon',b:'অপরাহ্ন (PM)',c:'time'},
{k:'はん',r:'han',e:'half past',b:'সাড়ে',c:'time'},
{k:'なんじ',r:'nanji',e:'what time',b:'কয়টা বাজে',c:'time'},
{k:'いつ',r:'itsu',e:'when',b:'কখন',c:'time'},
// ── Days ──
{k:'にちようび',r:'nichiyoubi',e:'Sunday',b:'রবিবার',c:'days'},
{k:'げつようび',r:'getsuyoubi',e:'Monday',b:'সোমবার',c:'days'},
{k:'かようび',r:'kayoubi',e:'Tuesday',b:'মঙ্গলবার',c:'days'},
{k:'すいようび',r:'suiyoubi',e:'Wednesday',b:'বুধবার',c:'days'},
{k:'もくようび',r:'mokuyoubi',e:'Thursday',b:'বৃহস্পতিবার',c:'days'},
{k:'きんようび',r:'kin\'youbi',e:'Friday',b:'শুক্রবার',c:'days'},
{k:'どようび',r:'doyoubi',e:'Saturday',b:'শনিবার',c:'days'},
{k:'なんようび',r:'nanyoubi',e:'what day',b:'কী বার',c:'days'},
// ── Months ──
{k:'いちがつ',r:'ichigatsu',e:'January',b:'জানুয়ারি',c:'months'},
{k:'にがつ',r:'nigatsu',e:'February',b:'ফেব্রুয়ারি',c:'months'},
{k:'さんがつ',r:'sangatsu',e:'March',b:'মার্চ',c:'months'},
{k:'しがつ',r:'shigatsu',e:'April',b:'এপ্রিল',c:'months'},
{k:'ごがつ',r:'gogatsu',e:'May',b:'মে',c:'months'},
{k:'ろくがつ',r:'rokugatsu',e:'June',b:'জুন',c:'months'},
{k:'しちがつ',r:'shichigatsu',e:'July',b:'জুলাই',c:'months'},
{k:'はちがつ',r:'hachigatsu',e:'August',b:'আগস্ট',c:'months'},
{k:'くがつ',r:'kugatsu',e:'September',b:'সেপ্টেম্বর',c:'months'},
{k:'じゅうがつ',r:'juugatsu',e:'October',b:'অক্টোবর',c:'months'},
{k:'じゅういちがつ',r:'juuichigatsu',e:'November',b:'নভেম্বর',c:'months'},
{k:'じゅうにがつ',r:'juunigatsu',e:'December',b:'ডিসেম্বর',c:'months'},
{k:'なんがつ',r:'nangatsu',e:'what month',b:'কত মাস',c:'months'},
// ── Family ──
{k:'かぞく',r:'kazoku',e:'family',b:'পরিবার',c:'family'},
{k:'ちち',r:'chichi',e:'my father',b:'আমার বাবা',c:'family'},
{k:'はは',r:'haha',e:'my mother',b:'আমার মা',c:'family'},
{k:'おとうさん',r:'otousan',e:"someone's father",b:'বাবা',c:'family'},
{k:'おかあさん',r:'okaasan',e:"someone's mother",b:'মা',c:'family'},
{k:'あに',r:'ani',e:'my older brother',b:'আমার বড় ভাই',c:'family'},
{k:'あね',r:'ane',e:'my older sister',b:'আমার বড় বোন',c:'family'},
{k:'おにいさん',r:'oniisan',e:"someone's older brother",b:'বড় ভাই',c:'family'},
{k:'おねえさん',r:'oneesan',e:"someone's older sister",b:'বড় বোন',c:'family'},
{k:'おとうと',r:'otouto',e:'younger brother',b:'ছোট ভাই',c:'family'},
{k:'いもうと',r:'imouto',e:'younger sister',b:'ছোট বোন',c:'family'},
{k:'そふ',r:'sofu',e:'my grandfather',b:'আমার দাদা',c:'family'},
{k:'そぼ',r:'sobo',e:'my grandmother',b:'আমার দাদি',c:'family'},
{k:'おじいさん',r:'ojiisan',e:'grandfather',b:'দাদা / নানা',c:'family'},
{k:'おばあさん',r:'obaasan',e:'grandmother',b:'দাদি / নানি',c:'family'},
{k:'おじさん',r:'ojisan',e:'uncle',b:'চাচা / মামা',c:'family'},
{k:'おばさん',r:'obasan',e:'aunt',b:'চাচি / মামি',c:'family'},
{k:'こども',r:'kodomo',e:'child',b:'শিশু',c:'family'},
{k:'おとこのこ',r:'otoko no ko',e:'boy',b:'ছেলে',c:'family'},
{k:'おんなのこ',r:'onna no ko',e:'girl',b:'মেয়ে',c:'family'},
{k:'ともだち',r:'tomodachi',e:'friend',b:'বন্ধু',c:'family'},
{k:'しゅじん',r:'shujin',e:'my husband',b:'আমার স্বামী',c:'family'},
{k:'つま',r:'tsuma',e:'my wife',b:'আমার স্ত্রী',c:'family'},
// ── Body ──
{k:'からだ',r:'karada',e:'body',b:'শরীর',c:'body'},
{k:'あたま',r:'atama',e:'head',b:'মাথা',c:'body'},
{k:'かお',r:'kao',e:'face',b:'মুখ',c:'body'},
{k:'め',r:'me',e:'eye',b:'চোখ',c:'body'},
{k:'はな',r:'hana',e:'nose',b:'নাক',c:'body'},
{k:'くち',r:'kuchi',e:'mouth',b:'মুখ',c:'body'},
{k:'みみ',r:'mimi',e:'ear',b:'কান',c:'body'},
{k:'かみ',r:'kami',e:'hair',b:'চুল',c:'body'},
{k:'は',r:'ha',e:'teeth',b:'দাঁত',c:'body'},
{k:'て',r:'te',e:'hand',b:'হাত',c:'body'},
{k:'あし',r:'ashi',e:'leg / foot',b:'পা',c:'body'},
{k:'せなか',r:'senaka',e:'back',b:'পিঠ',c:'body'},
{k:'おなか',r:'onaka',e:'stomach / belly',b:'পেট',c:'body'},
{k:'むね',r:'mune',e:'chest',b:'বুক',c:'body'},
{k:'のど',r:'nodo',e:'throat',b:'গলা',c:'body'},
{k:'ゆび',r:'yubi',e:'finger',b:'আঙুল',c:'body'},
{k:'ひざ',r:'hiza',e:'knee',b:'হাঁটু',c:'body'},
{k:'かた',r:'kata',e:'shoulder',b:'কাঁধ',c:'body'},
{k:'くび',r:'kubi',e:'neck',b:'ঘাড়',c:'body'},
// ── Food ──
{k:'ごはん',r:'gohan',e:'rice / meal',b:'ভাত / খাবার',c:'food'},
{k:'みず',r:'mizu',e:'water',b:'পানি',c:'food'},
{k:'おちゃ',r:'ocha',e:'tea',b:'চা',c:'food'},
{k:'パン',r:'pan',e:'bread',b:'রুটি',c:'food'},
{k:'たまご',r:'tamago',e:'egg',b:'ডিম',c:'food'},
{k:'にく',r:'niku',e:'meat',b:'মাংস',c:'food'},
{k:'さかな',r:'sakana',e:'fish',b:'মাছ',c:'food'},
{k:'やさい',r:'yasai',e:'vegetables',b:'সবজি',c:'food'},
{k:'くだもの',r:'kudamono',e:'fruit',b:'ফল',c:'food'},
{k:'すし',r:'sushi',e:'sushi',b:'সুশি',c:'food'},
{k:'みそしる',r:'misoshiru',e:'miso soup',b:'মিসো স্যুপ',c:'food'},
{k:'ラーメン',r:'raamen',e:'ramen noodles',b:'রামেন',c:'food'},
{k:'うどん',r:'udon',e:'udon noodles',b:'উদন',c:'food'},
{k:'てんぷら',r:'tenpura',e:'tempura',b:'টেম্পুরা',c:'food'},
{k:'コーヒー',r:'koohii',e:'coffee',b:'কফি',c:'food'},
{k:'ビール',r:'biiru',e:'beer',b:'বিয়ার',c:'food'},
{k:'ジュース',r:'juusu',e:'juice',b:'জুস',c:'food'},
{k:'ミルク',r:'miruku',e:'milk',b:'দুধ',c:'food'},
{k:'しお',r:'shio',e:'salt',b:'লবণ',c:'food'},
{k:'さとう',r:'satou',e:'sugar',b:'চিনি',c:'food'},
{k:'しょうゆ',r:'shouyu',e:'soy sauce',b:'সয়া সস',c:'food'},
{k:'バター',r:'bataa',e:'butter',b:'মাখন',c:'food'},
{k:'ケーキ',r:'keeki',e:'cake',b:'কেক',c:'food'},
{k:'りんご',r:'ringo',e:'apple',b:'আপেল',c:'food'},
{k:'バナナ',r:'banana',e:'banana',b:'কলা',c:'food'},
{k:'みかん',r:'mikan',e:'mandarin orange',b:'কমলালেবু',c:'food'},
{k:'いちご',r:'ichigo',e:'strawberry',b:'স্ট্রবেরি',c:'food'},
{k:'とうふ',r:'toufu',e:'tofu',b:'টোফু',c:'food'},
{k:'おさけ',r:'osake',e:'alcohol / sake',b:'মদ / সাকে',c:'food'},
{k:'スープ',r:'suupu',e:'soup',b:'স্যুপ',c:'food'},
// ── Colors ──
{k:'いろ',r:'iro',e:'color',b:'রং',c:'colors'},
{k:'あか',r:'aka',e:'red',b:'লাল',c:'colors'},
{k:'あお',r:'ao',e:'blue',b:'নীল',c:'colors'},
{k:'みどり',r:'midori',e:'green',b:'সবুজ',c:'colors'},
{k:'きいろ',r:'kiiro',e:'yellow',b:'হলুদ',c:'colors'},
{k:'しろ',r:'shiro',e:'white',b:'সাদা',c:'colors'},
{k:'くろ',r:'kuro',e:'black',b:'কালো',c:'colors'},
{k:'ちゃいろ',r:'chairo',e:'brown',b:'বাদামি',c:'colors'},
{k:'オレンジ',r:'orenji',e:'orange',b:'কমলা',c:'colors'},
{k:'むらさき',r:'murasaki',e:'purple',b:'বেগুনি',c:'colors'},
{k:'ピンク',r:'pinku',e:'pink',b:'গোলাপি',c:'colors'},
{k:'はいいろ',r:'haiiro',e:'gray',b:'ধূসর',c:'colors'},
// ── Places ──
{k:'いえ',r:'ie',e:'house',b:'বাড়ি',c:'places'},
{k:'うち',r:'uchi',e:'home / my place',b:'আমার বাড়ি',c:'places'},
{k:'がっこう',r:'gakkou',e:'school',b:'স্কুল',c:'places'},
{k:'だいがく',r:'daigaku',e:'university',b:'বিশ্ববিদ্যালয়',c:'places'},
{k:'えき',r:'eki',e:'train station',b:'রেলওয়ে স্টেশন',c:'places'},
{k:'びょういん',r:'byouin',e:'hospital',b:'হাসপাতাল',c:'places'},
{k:'みせ',r:'mise',e:'shop / store',b:'দোকান',c:'places'},
{k:'としょかん',r:'toshokan',e:'library',b:'লাইব্রেরি',c:'places'},
{k:'こうえん',r:'kouen',e:'park',b:'পার্ক',c:'places'},
{k:'レストラン',r:'resutoran',e:'restaurant',b:'রেস্তোরাঁ',c:'places'},
{k:'ぎんこう',r:'ginkou',e:'bank',b:'ব্যাংক',c:'places'},
{k:'ゆうびんきょく',r:'yuubinkyoku',e:'post office',b:'ডাকঘর',c:'places'},
{k:'スーパー',r:'suupaa',e:'supermarket',b:'সুপারমার্কেট',c:'places'},
{k:'デパート',r:'depaato',e:'department store',b:'ডিপার্টমেন্ট স্টোর',c:'places'},
{k:'コンビニ',r:'konbini',e:'convenience store',b:'কনভেনিয়েন্স স্টোর',c:'places'},
{k:'かいしゃ',r:'kaisha',e:'company / office',b:'কোম্পানি / অফিস',c:'places'},
{k:'くうこう',r:'kuukou',e:'airport',b:'বিমানবন্দর',c:'places'},
{k:'うみ',r:'umi',e:'sea / ocean',b:'সমুদ্র',c:'places'},
{k:'やま',r:'yama',e:'mountain',b:'পাহাড়',c:'places'},
{k:'かわ',r:'kawa',e:'river',b:'নদী',c:'places'},
{k:'みち',r:'michi',e:'road / street',b:'রাস্তা',c:'places'},
{k:'はし',r:'hashi',e:'bridge',b:'সেতু',c:'places'},
{k:'まち',r:'machi',e:'town / city',b:'শহর',c:'places'},
{k:'むら',r:'mura',e:'village',b:'গ্রাম',c:'places'},
{k:'くに',r:'kuni',e:'country',b:'দেশ',c:'places'},
// ── Verbs ──
{k:'たべます',r:'tabemasu',e:'to eat',b:'খাওয়া',c:'verbs'},
{k:'のみます',r:'nomimasu',e:'to drink',b:'পান করা',c:'verbs'},
{k:'いきます',r:'ikimasu',e:'to go',b:'যাওয়া',c:'verbs'},
{k:'きます',r:'kimasu',e:'to come',b:'আসা',c:'verbs'},
{k:'みます',r:'mimasu',e:'to see / watch',b:'দেখা',c:'verbs'},
{k:'ききます',r:'kikimasu',e:'to listen / ask',b:'শোনা / জিজ্ঞেস করা',c:'verbs'},
{k:'かきます',r:'kakimasu',e:'to write',b:'লেখা',c:'verbs'},
{k:'よみます',r:'yomimasu',e:'to read',b:'পড়া',c:'verbs'},
{k:'はなします',r:'hanashimasu',e:'to speak',b:'কথা বলা',c:'verbs'},
{k:'わかります',r:'wakarimasu',e:'to understand',b:'বোঝা',c:'verbs'},
{k:'します',r:'shimasu',e:'to do',b:'করা',c:'verbs'},
{k:'あります',r:'arimasu',e:'there is (thing)',b:'আছে (জিনিস)',c:'verbs'},
{k:'います',r:'imasu',e:'there is (living)',b:'আছে (জীব)',c:'verbs'},
{k:'かいます',r:'kaimasu',e:'to buy',b:'কেনা',c:'verbs'},
{k:'うります',r:'urimasu',e:'to sell',b:'বিক্রি করা',c:'verbs'},
{k:'もらいます',r:'moraimasu',e:'to receive',b:'পাওয়া',c:'verbs'},
{k:'あげます',r:'agemasu',e:'to give',b:'দেওয়া',c:'verbs'},
{k:'おきます',r:'okimasu',e:'to wake up',b:'ঘুম থেকে উঠা',c:'verbs'},
{k:'ねます',r:'nemasu',e:'to sleep',b:'ঘুমানো',c:'verbs'},
{k:'おわります',r:'owarimasu',e:'to finish',b:'শেষ করা',c:'verbs'},
{k:'はじめます',r:'hajimemasu',e:'to start',b:'শুরু করা',c:'verbs'},
{k:'つかいます',r:'tsukaimasu',e:'to use',b:'ব্যবহার করা',c:'verbs'},
{k:'あいます',r:'aimasu',e:'to meet',b:'দেখা করা',c:'verbs'},
{k:'まちます',r:'machimasu',e:'to wait',b:'অপেক্ষা করা',c:'verbs'},
{k:'はいります',r:'hairimasu',e:'to enter',b:'প্রবেশ করা',c:'verbs'},
{k:'でます',r:'demasu',e:'to exit / leave',b:'বের হওয়া',c:'verbs'},
{k:'のります',r:'norimasu',e:'to ride / get on',b:'উঠা (যানবাহনে)',c:'verbs'},
{k:'おります',r:'orimasu',e:'to get off',b:'নামা',c:'verbs'},
{k:'あるきます',r:'arukimasu',e:'to walk',b:'হাঁটা',c:'verbs'},
{k:'はしります',r:'hashirimasu',e:'to run',b:'দৌড়ানো',c:'verbs'},
{k:'およぎます',r:'oyogimasu',e:'to swim',b:'সাঁতার কাটা',c:'verbs'},
{k:'うたいます',r:'utaimasu',e:'to sing',b:'গান গাওয়া',c:'verbs'},
{k:'あそびます',r:'asobimasu',e:'to play',b:'খেলা',c:'verbs'},
{k:'べんきょうします',r:'benkyou shimasu',e:'to study',b:'পড়াশোনা করা',c:'verbs'},
{k:'しごとします',r:'shigoto shimasu',e:'to work',b:'কাজ করা',c:'verbs'},
{k:'でんわします',r:'denwa shimasu',e:'to phone',b:'ফোন করা',c:'verbs'},
{k:'きります',r:'kirimasu',e:'to cut',b:'কাটা',c:'verbs'},
{k:'つくります',r:'tsukurimasu',e:'to make / create',b:'বানানো',c:'verbs'},
{k:'あけます',r:'akemasu',e:'to open',b:'খোলা',c:'verbs'},
{k:'しめます',r:'shimemasu',e:'to close',b:'বন্ধ করা',c:'verbs'},
{k:'つけます',r:'tsukemasu',e:'to turn on',b:'চালু করা',c:'verbs'},
{k:'けします',r:'keshimasu',e:'to turn off / erase',b:'বন্ধ করা / মুছা',c:'verbs'},
{k:'おしえます',r:'oshiemasu',e:'to teach / tell',b:'শেখানো / বলা',c:'verbs'},
{k:'おぼえます',r:'oboemasu',e:'to memorize',b:'মনে রাখা',c:'verbs'},
{k:'わすれます',r:'wasuremasu',e:'to forget',b:'ভুলে যাওয়া',c:'verbs'},
{k:'かえります',r:'kaerimasu',e:'to return home',b:'বাড়ি ফেরা',c:'verbs'},
{k:'もちます',r:'mochimasu',e:'to hold / carry',b:'ধরা / বহন করা',c:'verbs'},
{k:'おくります',r:'okurimasu',e:'to send',b:'পাঠানো',c:'verbs'},
{k:'でかけます',r:'dekakemasu',e:'to go out',b:'বাইরে যাওয়া',c:'verbs'},
{k:'やすみます',r:'yasumimasu',e:'to rest',b:'বিশ্রাম নেওয়া',c:'verbs'},
{k:'すわります',r:'suwarimasu',e:'to sit down',b:'বসা',c:'verbs'},
{k:'たちます',r:'tachimasu',e:'to stand up',b:'দাঁড়ানো',c:'verbs'},
{k:'しります',r:'shirimasu',e:'to know',b:'জানা',c:'verbs'},
{k:'おもいます',r:'omoimasu',e:'to think',b:'মনে করা',c:'verbs'},
{k:'いいます',r:'iimasu',e:'to say',b:'বলা',c:'verbs'},
{k:'かえします',r:'kaeshimasu',e:'to return (something)',b:'ফেরত দেওয়া',c:'verbs'},
{k:'かります',r:'karimasu',e:'to borrow',b:'ধার নেওয়া',c:'verbs'},
{k:'みせます',r:'misemasu',e:'to show',b:'দেখানো',c:'verbs'},
{k:'とります',r:'torimasu',e:'to take',b:'নেওয়া',c:'verbs'},
// ── Adjectives ──
{k:'おおきい',r:'ookii',e:'big / large',b:'বড়',c:'adjectives'},
{k:'ちいさい',r:'chiisai',e:'small',b:'ছোট',c:'adjectives'},
{k:'あたらしい',r:'atarashii',e:'new',b:'নতুন',c:'adjectives'},
{k:'ふるい',r:'furui',e:'old',b:'পুরনো',c:'adjectives'},
{k:'たかい',r:'takai',e:'expensive / tall',b:'দামি / উঁচু',c:'adjectives'},
{k:'やすい',r:'yasui',e:'cheap',b:'সস্তা',c:'adjectives'},
{k:'おいしい',r:'oishii',e:'delicious',b:'সুস্বাদু',c:'adjectives'},
{k:'まずい',r:'mazui',e:'bad tasting',b:'বাজে স্বাদ',c:'adjectives'},
{k:'たのしい',r:'tanoshii',e:'fun / enjoyable',b:'মজাদার',c:'adjectives'},
{k:'むずかしい',r:'muzukashii',e:'difficult',b:'কঠিন',c:'adjectives'},
{k:'やさしい',r:'yasashii',e:'easy / kind',b:'সহজ / দয়ালু',c:'adjectives'},
{k:'いい / よい',r:'ii / yoi',e:'good',b:'ভালো',c:'adjectives'},
{k:'わるい',r:'warui',e:'bad',b:'খারাপ',c:'adjectives'},
{k:'おもしろい',r:'omoshiroi',e:'interesting / funny',b:'মজাদার / আকর্ষণীয়',c:'adjectives'},
{k:'つまらない',r:'tsumaranai',e:'boring',b:'বিরক্তিকর',c:'adjectives'},
{k:'あつい',r:'atsui',e:'hot',b:'গরম',c:'adjectives'},
{k:'さむい',r:'samui',e:'cold (weather)',b:'ঠান্ডা (আবহাওয়া)',c:'adjectives'},
{k:'つめたい',r:'tsumetai',e:'cold (to touch)',b:'ঠান্ডা (স্পর্শে)',c:'adjectives'},
{k:'あたたかい',r:'atatakai',e:'warm',b:'উষ্ণ',c:'adjectives'},
{k:'すずしい',r:'suzushii',e:'cool',b:'শীতল',c:'adjectives'},
{k:'はやい',r:'hayai',e:'fast / early',b:'দ্রুত / সকাল',c:'adjectives'},
{k:'おそい',r:'osoi',e:'slow / late',b:'ধীর / দেরি',c:'adjectives'},
{k:'ながい',r:'nagai',e:'long',b:'লম্বা',c:'adjectives'},
{k:'みじかい',r:'mijikai',e:'short',b:'ছোট',c:'adjectives'},
{k:'ひろい',r:'hiroi',e:'wide / spacious',b:'প্রশস্ত',c:'adjectives'},
{k:'せまい',r:'semai',e:'narrow',b:'সংকীর্ণ',c:'adjectives'},
{k:'おもい',r:'omoi',e:'heavy',b:'ভারী',c:'adjectives'},
{k:'かるい',r:'karui',e:'light (weight)',b:'হালকা',c:'adjectives'},
{k:'あかるい',r:'akarui',e:'bright',b:'উজ্জ্বল',c:'adjectives'},
{k:'くらい',r:'kurai',e:'dark',b:'অন্ধকার',c:'adjectives'},
{k:'うれしい',r:'ureshii',e:'happy / glad',b:'আনন্দিত',c:'adjectives'},
{k:'かなしい',r:'kanashii',e:'sad',b:'দুঃখিত',c:'adjectives'},
{k:'こわい',r:'kowai',e:'scary',b:'ভীতিকর',c:'adjectives'},
{k:'いたい',r:'itai',e:'painful',b:'বেদনাদায়ক',c:'adjectives'},
{k:'からい',r:'karai',e:'spicy',b:'ঝাল',c:'adjectives'},
{k:'あまい',r:'amai',e:'sweet',b:'মিষ্টি',c:'adjectives'},
{k:'すっぱい',r:'suppai',e:'sour',b:'টক',c:'adjectives'},
{k:'にがい',r:'nigai',e:'bitter',b:'তেতো',c:'adjectives'},
{k:'かわいい',r:'kawaii',e:'cute',b:'কিউট / আদুরে',c:'adjectives'},
{k:'きれい',r:'kirei',e:'beautiful / clean',b:'সুন্দর / পরিষ্কার',c:'adjectives'},
{k:'にぎやか',r:'nigiyaka',e:'lively / bustling',b:'প্রাণবন্ত',c:'adjectives'},
{k:'しずか',r:'shizuka',e:'quiet',b:'শান্ত',c:'adjectives'},
{k:'べんり',r:'benri',e:'convenient',b:'সুবিধাজনক',c:'adjectives'},
{k:'すき',r:'suki',e:'liked / favorite',b:'পছন্দের',c:'adjectives'},
{k:'きらい',r:'kirai',e:'disliked',b:'অপছন্দের',c:'adjectives'},
{k:'じょうず',r:'jouzu',e:'good at (skill)',b:'দক্ষ',c:'adjectives'},
{k:'へた',r:'heta',e:'bad at (skill)',b:'অদক্ষ',c:'adjectives'},
{k:'げんき',r:'genki',e:'healthy / energetic',b:'সুস্থ / প্রাণবন্ত',c:'adjectives'},
{k:'たいせつ',r:'taisetsu',e:'important',b:'গুরুত্বপূর্ণ',c:'adjectives'},
{k:'ゆうめい',r:'yuumei',e:'famous',b:'বিখ্যাত',c:'adjectives'},
{k:'しんせつ',r:'shinsetsu',e:'kind / gentle',b:'সদয় / দয়ালু',c:'adjectives'},
{k:'まじめ',r:'majime',e:'serious / diligent',b:'গুরুগম্ভীর / পরিশ্রমী',c:'adjectives'},
{k:'たいへん',r:'taihen',e:'terrible / very',b:'ভয়াবহ / খুব',c:'adjectives'},
// ── Daily Life Nouns ──
{k:'でんわ',r:'denwa',e:'telephone',b:'টেলিফোন',c:'daily'},
{k:'スマホ',r:'sumaho',e:'smartphone',b:'স্মার্টফোন',c:'daily'},
{k:'テレビ',r:'terebi',e:'television',b:'টেলিভিশন',c:'daily'},
{k:'ラジオ',r:'rajio',e:'radio',b:'রেডিও',c:'daily'},
{k:'パソコン',r:'pasokon',e:'computer / PC',b:'কম্পিউটার',c:'daily'},
{k:'カメラ',r:'kamera',e:'camera',b:'ক্যামেরা',c:'daily'},
{k:'じてんしゃ',r:'jitensha',e:'bicycle',b:'সাইকেল',c:'daily'},
{k:'くるま',r:'kuruma',e:'car',b:'গাড়ি',c:'daily'},
{k:'バス',r:'basu',e:'bus',b:'বাস',c:'daily'},
{k:'でんしゃ',r:'densha',e:'train',b:'ট্রেন',c:'daily'},
{k:'タクシー',r:'takushii',e:'taxi',b:'ট্যাক্সি',c:'daily'},
{k:'ひこうき',r:'hikouki',e:'airplane',b:'বিমান',c:'daily'},
{k:'ふね',r:'fune',e:'ship / boat',b:'জাহাজ / নৌকা',c:'daily'},
{k:'ほん',r:'hon',e:'book',b:'বই',c:'daily'},
{k:'ざっし',r:'zasshi',e:'magazine',b:'ম্যাগাজিন',c:'daily'},
{k:'しんぶん',r:'shinbun',e:'newspaper',b:'সংবাদপত্র',c:'daily'},
{k:'てがみ',r:'tegami',e:'letter',b:'চিঠি',c:'daily'},
{k:'かばん',r:'kaban',e:'bag',b:'ব্যাগ',c:'daily'},
{k:'さいふ',r:'saifu',e:'wallet',b:'মানিব্যাগ',c:'daily'},
{k:'かぎ',r:'kagi',e:'key',b:'চাবি',c:'daily'},
{k:'めがね',r:'megane',e:'glasses',b:'চশমা',c:'daily'},
{k:'かさ',r:'kasa',e:'umbrella',b:'ছাতা',c:'daily'},
{k:'とけい',r:'tokei',e:'watch / clock',b:'ঘড়ি',c:'daily'},
{k:'くすり',r:'kusuri',e:'medicine',b:'ওষুধ',c:'daily'},
{k:'きっぷ',r:'kippu',e:'ticket',b:'টিকেট',c:'daily'},
{k:'おかね',r:'okane',e:'money',b:'টাকা',c:'daily'},
{k:'にもつ',r:'nimotsu',e:'luggage',b:'মালপত্র',c:'daily'},
{k:'でんき',r:'denki',e:'electricity / light',b:'বিদ্যুৎ / আলো',c:'daily'},
{k:'まど',r:'mado',e:'window',b:'জানালা',c:'daily'},
{k:'ドア',r:'doa',e:'door',b:'দরজা',c:'daily'},
{k:'つくえ',r:'tsukue',e:'desk',b:'ডেস্ক',c:'daily'},
{k:'いす',r:'isu',e:'chair',b:'চেয়ার',c:'daily'},
{k:'テーブル',r:'teeburu',e:'table',b:'টেবিল',c:'daily'},
{k:'ベッド',r:'beddo',e:'bed',b:'বিছানা',c:'daily'},
{k:'れいぞうこ',r:'reizouko',e:'refrigerator',b:'ফ্রিজ',c:'daily'},
// ── Clothing ──
{k:'ふく',r:'fuku',e:'clothes',b:'পোশাক',c:'clothing'},
{k:'シャツ',r:'shatsu',e:'shirt',b:'শার্ট',c:'clothing'},
{k:'ズボン',r:'zubon',e:'trousers',b:'প্যান্ট / ট্রাউজার',c:'clothing'},
{k:'スカート',r:'sukaato',e:'skirt',b:'স্কার্ট',c:'clothing'},
{k:'ワンピース',r:'wanpiisu',e:'dress',b:'ড্রেস',c:'clothing'},
{k:'うわぎ',r:'uwagi',e:'jacket / coat',b:'জ্যাকেট / কোট',c:'clothing'},
{k:'コート',r:'kooto',e:'coat',b:'কোট',c:'clothing'},
{k:'ぼうし',r:'boushi',e:'hat / cap',b:'টুপি',c:'clothing'},
{k:'くつ',r:'kutsu',e:'shoes',b:'জুতা',c:'clothing'},
{k:'くつした',r:'kutsushita',e:'socks',b:'মোজা',c:'clothing'},
{k:'ネクタイ',r:'nekutai',e:'necktie',b:'টাই',c:'clothing'},
{k:'ゆびわ',r:'yubiwa',e:'ring',b:'আংটি',c:'clothing'},
// ── Nature ──
{k:'てんき',r:'tenki',e:'weather',b:'আবহাওয়া',c:'nature'},
{k:'はれ',r:'hare',e:'sunny / clear',b:'রোদেলা',c:'nature'},
{k:'くもり',r:'kumori',e:'cloudy',b:'মেঘলা',c:'nature'},
{k:'あめ',r:'ame',e:'rain',b:'বৃষ্টি',c:'nature'},
{k:'ゆき',r:'yuki',e:'snow',b:'তুষার',c:'nature'},
{k:'かぜ',r:'kaze',e:'wind',b:'বাতাস',c:'nature'},
{k:'きせつ',r:'kisetsu',e:'season',b:'মৌসুম',c:'nature'},
{k:'はる',r:'haru',e:'spring',b:'বসন্ত',c:'nature'},
{k:'なつ',r:'natsu',e:'summer',b:'গ্রীষ্ম',c:'nature'},
{k:'あき',r:'aki',e:'autumn / fall',b:'শরৎ',c:'nature'},
{k:'ふゆ',r:'fuyu',e:'winter',b:'শীতকাল',c:'nature'},
{k:'そら',r:'sora',e:'sky',b:'আকাশ',c:'nature'},
{k:'くも',r:'kumo',e:'cloud',b:'মেঘ',c:'nature'},
{k:'たいよう',r:'taiyou',e:'sun',b:'সূর্য',c:'nature'},
{k:'つき',r:'tsuki',e:'moon',b:'চাঁদ',c:'nature'},
{k:'ほし',r:'hoshi',e:'star',b:'তারা',c:'nature'},
{k:'き',r:'ki',e:'tree',b:'গাছ',c:'nature'},
{k:'はな',r:'hana',e:'flower',b:'ফুল',c:'nature'},
{k:'くさ',r:'kusa',e:'grass',b:'ঘাস',c:'nature'},
{k:'いし',r:'ishi',e:'stone / rock',b:'পাথর',c:'nature'},
{k:'いけ',r:'ike',e:'pond',b:'পুকুর',c:'nature'},
{k:'もり',r:'mori',e:'forest',b:'বন',c:'nature'},
// ── School ──
{k:'がっこう',r:'gakkou',e:'school',b:'স্কুল',c:'school'},
{k:'だいがく',r:'daigaku',e:'university',b:'বিশ্ববিদ্যালয়',c:'school'},
{k:'きょうしつ',r:'kyoushitsu',e:'classroom',b:'শ্রেণিকক্ষ',c:'school'},
{k:'せんせい',r:'sensei',e:'teacher',b:'শিক্ষক',c:'school'},
{k:'がくせい',r:'gakusei',e:'student',b:'ছাত্র',c:'school'},
{k:'べんきょう',r:'benkyou',e:'study',b:'পড়াশোনা',c:'school'},
{k:'しゅくだい',r:'shukudai',e:'homework',b:'বাড়ির কাজ',c:'school'},
{k:'テスト',r:'tesuto',e:'test',b:'পরীক্ষা',c:'school'},
{k:'しけん',r:'shiken',e:'exam',b:'পরীক্ষা',c:'school'},
{k:'ノート',r:'nooto',e:'notebook',b:'নোটবুক',c:'school'},
{k:'えんぴつ',r:'enpitsu',e:'pencil',b:'পেন্সিল',c:'school'},
{k:'ペン',r:'pen',e:'pen',b:'কলম',c:'school'},
{k:'けしごむ',r:'keshigomu',e:'eraser',b:'ইরেজার',c:'school'},
{k:'じしょ',r:'jisho',e:'dictionary',b:'অভিধান',c:'school'},
{k:'きょうかしょ',r:'kyoukasho',e:'textbook',b:'পাঠ্যপুস্তক',c:'school'},
{k:'クラス',r:'kurasu',e:'class',b:'ক্লাস',c:'school'},
// ── Animals ──
{k:'いぬ',r:'inu',e:'dog',b:'কুকুর',c:'animals'},
{k:'ねこ',r:'neko',e:'cat',b:'বিড়াল',c:'animals'},
{k:'とり',r:'tori',e:'bird',b:'পাখি',c:'animals'},
{k:'うさぎ',r:'usagi',e:'rabbit',b:'খরগোশ',c:'animals'},
{k:'うし',r:'ushi',e:'cow',b:'গরু',c:'animals'},
{k:'ぶた',r:'buta',e:'pig',b:'শুকর',c:'animals'},
{k:'にわとり',r:'niwatori',e:'chicken',b:'মুরগি',c:'animals'},
{k:'うま',r:'uma',e:'horse',b:'ঘোড়া',c:'animals'},
{k:'さる',r:'saru',e:'monkey',b:'বানর',c:'animals'},
{k:'ぞう',r:'zou',e:'elephant',b:'হাতি',c:'animals'},
{k:'くま',r:'kuma',e:'bear',b:'ভালুক',c:'animals'},
{k:'へび',r:'hebi',e:'snake',b:'সাপ',c:'animals'},
{k:'かめ',r:'kame',e:'turtle',b:'কচ্ছপ',c:'animals'},
{k:'むし',r:'mushi',e:'insect / bug',b:'পোকা',c:'animals'},
{k:'ライオン',r:'raion',e:'lion',b:'সিংহ',c:'animals'},
{k:'さかな',r:'sakana',e:'fish',b:'মাছ',c:'animals'},
// ── Directions ──
{k:'みぎ',r:'migi',e:'right',b:'ডান',c:'directions'},
{k:'ひだり',r:'hidari',e:'left',b:'বাম',c:'directions'},
{k:'まえ',r:'mae',e:'front / before',b:'সামনে',c:'directions'},
{k:'うしろ',r:'ushiro',e:'behind / back',b:'পিছনে',c:'directions'},
{k:'うえ',r:'ue',e:'above / up',b:'উপরে',c:'directions'},
{k:'した',r:'shita',e:'below / down',b:'নিচে',c:'directions'},
{k:'となり',r:'tonari',e:'next to',b:'পাশে',c:'directions'},
{k:'ちかく',r:'chikaku',e:'near',b:'কাছে',c:'directions'},
{k:'とおく',r:'tooku',e:'far',b:'দূরে',c:'directions'},
{k:'なか',r:'naka',e:'inside',b:'ভেতরে',c:'directions'},
{k:'そと',r:'soto',e:'outside',b:'বাইরে',c:'directions'},
{k:'あいだ',r:'aida',e:'between',b:'মাঝে',c:'directions'},
{k:'まっすぐ',r:'massugu',e:'straight',b:'সোজা',c:'directions'},
{k:'きた',r:'kita',e:'north',b:'উত্তর',c:'directions'},
{k:'みなみ',r:'minami',e:'south',b:'দক্ষিণ',c:'directions'},
{k:'ひがし',r:'higashi',e:'east',b:'পূর্ব',c:'directions'},
{k:'にし',r:'nishi',e:'west',b:'পশ্চিম',c:'directions'},
// ── Question Words ──
{k:'なに / なん',r:'nani / nan',e:'what',b:'কী',c:'questions'},
{k:'どこ',r:'doko',e:'where',b:'কোথায়',c:'questions'},
{k:'だれ',r:'dare',e:'who',b:'কে',c:'questions'},
{k:'いつ',r:'itsu',e:'when',b:'কখন',c:'questions'},
{k:'どれ',r:'dore',e:'which one',b:'কোনটি',c:'questions'},
{k:'どう',r:'dou',e:'how',b:'কীভাবে',c:'questions'},
{k:'どんな',r:'donna',e:'what kind',b:'কেমন',c:'questions'},
{k:'なぜ / どうして',r:'naze / doushite',e:'why',b:'কেন',c:'questions'},
{k:'いくら',r:'ikura',e:'how much (price)',b:'কত টাকা',c:'questions'},
{k:'いくつ',r:'ikutsu',e:'how many',b:'কতটি',c:'questions'},
{k:'なんさい',r:'nansai',e:'how old',b:'কত বছর বয়স',c:'questions'},
{k:'どちら',r:'dochira',e:'which (polite)',b:'কোনটি (বিনয়ী)',c:'questions'},
// ── Adverbs ──
{k:'とても',r:'totemo',e:'very',b:'খুব',c:'adverbs'},
{k:'あまり',r:'amari',e:'not very (+ negative)',b:'খুব একটা না',c:'adverbs'},
{k:'すこし',r:'sukoshi',e:'a little',b:'একটু',c:'adverbs'},
{k:'たくさん',r:'takusan',e:'a lot / many',b:'অনেক',c:'adverbs'},
{k:'もっと',r:'motto',e:'more',b:'আরও',c:'adverbs'},
{k:'もう',r:'mou',e:'already / anymore',b:'ইতোমধ্যে / আর না',c:'adverbs'},
{k:'まだ',r:'mada',e:'still / not yet',b:'এখনও',c:'adverbs'},
{k:'いつも',r:'itsumo',e:'always',b:'সবসময়',c:'adverbs'},
{k:'ときどき',r:'tokidoki',e:'sometimes',b:'মাঝে মাঝে',c:'adverbs'},
{k:'たいてい',r:'taitei',e:'usually',b:'সাধারণত',c:'adverbs'},
{k:'よく',r:'yoku',e:'often / well',b:'প্রায়ই / ভালোভাবে',c:'adverbs'},
{k:'ぜんぜん',r:'zenzen',e:'not at all (+ negative)',b:'মোটেও না',c:'adverbs'},
{k:'はじめて',r:'hajimete',e:'for the first time',b:'প্রথমবার',c:'adverbs'},
{k:'もちろん',r:'mochiron',e:'of course',b:'অবশ্যই',c:'adverbs'},
{k:'たぶん',r:'tabun',e:'probably / maybe',b:'সম্ভবত',c:'adverbs'},
{k:'ほんとうに',r:'hontouni',e:'really / truly',b:'সত্যিই',c:'adverbs'},
{k:'ちょっと',r:'chotto',e:'a little / just a moment',b:'একটু / একটু অপেক্ষা',c:'adverbs'},
{k:'ゆっくり',r:'yukkuri',e:'slowly',b:'ধীরে ধীরে',c:'adverbs'},
{k:'はやく',r:'hayaku',e:'quickly / early',b:'দ্রুত',c:'adverbs'},
{k:'いっしょに',r:'issho ni',e:'together',b:'একসাথে',c:'adverbs'},
{k:'ひとりで',r:'hitori de',e:'alone',b:'একা',c:'adverbs'},
{k:'ちょうど',r:'choudo',e:'exactly / just',b:'ঠিক',c:'adverbs'},
{k:'だいたい',r:'daitai',e:'approximately',b:'প্রায়',c:'adverbs'},
];
